services:
  ncat:
    build:
      context: .
      dockerfile: Dockerfile
    image: no-code-architects-toolkit
    ports:
      - "8081:8081"
    environment:
      API_KEY: ${API_KEY}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      LOCAL_STORAGE_PATH: ${LOCAL_STORAGE_PATH}
      MAX_QUEUE_LENGTH: ${MAX_QUEUE_LENGTH}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT}
    depends_on:
      - minio

  minio:
    build:
      context: .
      dockerfile: Dockerfile.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
