version: '3.8'
services:
  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    ports:
      - "8080:8080"
    environment:
      API_KEY: your_api_key
      S3_ENDPOINT_URL: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET_NAME: ncat-bucket
      S3_REGION: us-east-1
      LOCAL_STORAGE_PATH: /tmp
      MAX_QUEUE_LENGTH: 10
      GUNICORN_WORKERS: 4
      GUNICORN_TIMEOUT: 300
    depends_on:
      - minio

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:
